### PR TITLE
Add link to slides

### PR DESCRIPTION
**Pull request by ReblochonMasque**
Probably useful to have this link there

### CODE REVIEW

**Comment by brysontyrrell** [comment]
I like adding the link to the slides, but make the link more attractive and I’ll merge the change. 🙂

**Comment by ReblochonMasque** [comment]
Done!

**Comment by brysontyrrell** [comment]
I've gone ahead and added the link in a more family friendly format.

**Comment by ReblochonMasque** [comment]
Sure, some repos are more contributor friendly than others.
You are very welcomed!

**Pull request closed without merging**
